/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dialog;
import Beans.EinheitsVektor;
import Beans.Option;
import Beans.Position;
import Beans.Player;
import Client.LobbyGUI;
import Client.StartMenuGUI;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import models.SpielerListModel;
/**
 *
 * @author Leonardo
 */
public class NewPlayerDlg extends javax.swing.JDialog {
    private Dimension screensize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    private int hoeheSchirm = (int) screensize.getHeight();
    private int breiteSchirm = (int) screensize.getWidth();

    private String name = null;
    private Color c;

    private Player p;

    private SpielerListModel slm = new SpielerListModel();

    private int index = 0;

    private Image ship = null;
    private String shiffArt = "";
    private Option o;
    /**
     * Creates new form NewPlayerDlg
     */
    public NewPlayerDlg(StartMenuGUI parent, boolean modal, Option o) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
//        this.jlMyPlayerListe.setModel(slm);
        this.o = o;
    }


    public void clearAuswahl() {
        ship = null;
        shiffArt = "";
        p = null;
        c = null;
        name = null;
        this.tfName.setText("");
        this.btFarbe.setBackground(null);
        this.btSchiff.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btFarbe = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btSchiff = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btBeitreten = new javax.swing.JButton();
        btBeenden = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(688, 387));

        jPanel2.setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Name:");
        jPanel2.add(jLabel1);

        tfName.setFont(new java.awt.Font("Old English Text MT", 1, 18)); // NOI18N
        jPanel2.add(tfName);

        jLabel2.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Farbe:");
        jPanel2.add(jLabel2);

        btFarbe.setBorder(null);
        btFarbe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFarbeActionPerformed(evt);
            }
        });
        jPanel2.add(btFarbe);

        jLabel3.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Schiff:");
        jPanel2.add(jLabel3);

        btSchiff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSchiffActionPerformed(evt);
            }
        });
        jPanel2.add(btSchiff);

        jPanel3.setLayout(new java.awt.GridLayout(1, 1));

        btBeitreten.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        btBeitreten.setText("Beitreten");
        btBeitreten.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btBeitreten.setContentAreaFilled(false);
        btBeitreten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onBeitreten(evt);
            }
        });
        jPanel3.add(btBeitreten);

        btBeenden.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        btBeenden.setText("Beenden");
        btBeenden.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btBeenden.setContentAreaFilled(false);
        btBeenden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBeendenActionPerformed(evt);
            }
        });
        jPanel3.add(btBeenden);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFarbeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFarbeActionPerformed
        ColorChooserDlg cdlg = new ColorChooserDlg(this, true);
        cdlg.setVisible(true);
        if (cdlg.isC()) {
            c = cdlg.getC();
            this.btFarbe.setOpaque(true);
            this.btFarbe.setBackground(c);
        } else {
            System.out.println("Fehler bei der Farbübergabe!!!");
        }
    }//GEN-LAST:event_btFarbeActionPerformed

    private void btSchiffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSchiffActionPerformed
        ShipChooserDlg scdlg = new ShipChooserDlg(this, true);
        scdlg.setVisible(true);

        if (scdlg.issok()) {
            ship = scdlg.getSelectedShip();
            shiffArt = scdlg.getshipName();
            this.btSchiff.setText(shiffArt);
        }
    }//GEN-LAST:event_btSchiffActionPerformed

    private void btBeendenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBeendenActionPerformed
        dispose();
    }//GEN-LAST:event_btBeendenActionPerformed

    private void onBeitreten(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onBeitreten
                //Erstellen-----------------------------
                this.name = this.tfName.getText();
                if ((!name.equals("")) && ship != null) {
                     this.dispose();
                     
                     p = new Player(this.name, c, ship, o.getLeben(), o.getMunition(), -1, null, shiffArt, 90, new EinheitsVektor(1, 0), o.getSpeed(), o.getRadius(),null);
                                          
                } 
                else{
                    JOptionPane.showMessageDialog(null, "Bitte geben Sie alle Daten ein!");
                }
                
                //Beitreten-------------------------------
                        this.dispose();
                        LobbyGUI gg = new LobbyGUI(p);
            // Spieler muss vom Server noch Folgende Eigenschaften bekommen: position, pos, startPos, angle, Einheitsvektor
                        gg.setVisible(true);

                    
    }//GEN-LAST:event_onBeitreten

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewPlayerDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewPlayerDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewPlayerDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewPlayerDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewPlayerDlg dialog = new NewPlayerDlg(new StartMenuGUI(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBeenden;
    private javax.swing.JButton btBeitreten;
    private javax.swing.JButton btFarbe;
    private javax.swing.JButton btSchiff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
